### ISSUE TITLE
Linux make Error

### ISSUE THREAD

**Issue by Malifick** [mhetrick/hetrickcv#1]
../../include/engine.hpp:33:8: note:   candidate expects 1 argument, 4 provided
src/LogicInvert.cpp: In member function ‘virtual void LogicInvert::step()’:
src/LogicInvert.cpp:80:5: error: ‘lights’ was not declared in this scope
     lights[OUT1_LIGHT].value = outs[0];
     ^~~~~~
src/LogicInvert.cpp:80:5: note: suggested alternative: ‘LightIds’
     lights[OUT1_LIGHT].value = outs[0];
     ^~~~~~
     LightIds
src/LogicInvert.cpp: In constructor ‘LogicInvertWidget::LogicInvertWidget()’:
src/LogicInvert.cpp:126:14: error: ‘createLight’ was not declared in this scope
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 68), module, LogicInvert::OUT1_LIGHT));
              ^~~~~~~~~~~
src/LogicInvert.cpp:126:37: error: ‘RedLight’ was not declared in this scope
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 68), module, LogicInvert::OUT1_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:126:37: note: suggested alternative: ‘glLighti’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 68), module, LogicInvert::OUT1_LIGHT));
                                     ^~~~~~~~
                                     glLighti
src/LogicInvert.cpp:126:37: error: template argument 1 is invalid
src/LogicInvert.cpp:126:82: warning: right operand of comma operator has no effect [-Wunused-value]
 createLight<SmallLight<RedLight>>(Vec(74, 68), module, LogicInvert::OUT1_LIGHT));
                                                                     ^~~~~~~~~~
src/LogicInvert.cpp:127:37: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 113), module, LogicInvert::OUT2_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:127:37: note:   expected a type, got ‘RedLight’
src/LogicInvert.cpp:127:83: warning: right operand of comma operator has no effect [-Wunused-value]
 reateLight<SmallLight<RedLight>>(Vec(74, 113), module, LogicInvert::OUT2_LIGHT));
                                                                     ^~~~~~~~~~
src/LogicInvert.cpp:128:37: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 158), module, LogicInvert::OUT3_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:128:37: note:   expected a type, got ‘RedLight’
src/LogicInvert.cpp:128:83: warning: right operand of comma operator has no effect [-Wunused-value]
 reateLight<SmallLight<RedLight>>(Vec(74, 158), module, LogicInvert::OUT3_LIGHT));
                                                                     ^~~~~~~~~~
src/LogicInvert.cpp:129:37: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 203), module, LogicInvert::OUT4_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:129:37: note:   expected a type, got ‘RedLight’
src/LogicInvert.cpp:129:83: warning: right operand of comma operator has no effect [-Wunused-value]
 reateLight<SmallLight<RedLight>>(Vec(74, 203), module, LogicInvert::OUT4_LIGHT));
                                                                     ^~~~~~~~~~
src/LogicInvert.cpp:130:37: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 248), module, LogicInvert::OUT5_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:130:37: note:   expected a type, got ‘RedLight’
src/LogicInvert.cpp:130:83: warning: right operand of comma operator has no effect [-Wunused-value]
 reateLight<SmallLight<RedLight>>(Vec(74, 248), module, LogicInvert::OUT5_LIGHT));
                                                                     ^~~~~~~~~~
src/LogicInvert.cpp:131:37: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createLight<SmallLight<RedLight>>(Vec(74, 293), module, LogicInvert::OUT6_LIGHT));
                                     ^~~~~~~~
src/LogicInvert.cpp:131:37: note:   expected a type, got ‘RedLight’
src/LogicInvert.cpp:131:83: warning: right operand of comma operator has no effect [-Wunused-value]
 reateLight<SmallLight<RedLight>>(Vec(74, 293), module, LogicInvert::OUT6_LIGHT));
                                                                     ^~~~~~~~~~
make: *** [../../compile.mk:55: build/src/LogicInvert.cpp.o] Error 1

**Comment by mhetrick** [comment]
It looks like you may be compiling against a different version of Rack. Which commit are you on for Rack? I rewrote the lights recently to be compatible with the new system. I'm currently compiling it against this commit: https://github.com/VCVRack/Rack/commit/0c386dd52629a5f53d483e93f51b3e8b64f612a6

**Comment by Malifick** [comment]
just the commit that is on github for vcvrack .
it's about a week old now

**Comment by mhetrick** [comment]
I ended up removing Logic Invert to replace it with Gate Junction. Could you try pulling both the Rack and HetrickCV repos and compiling again?

Make sure that you do a `make clean` on the HetrickCV repo. I had issues the first time the lighting system changed because it still had some old object files laying around.

**Comment by Malifick** [comment]
I just finished compiling rack and the fundamental stuff like audibles and eseries and befaco , will try  it again :)

**Comment by Malifick** [comment]
Worked perfectly

**Comment by mhetrick** [comment]
Great, thanks!
