### ISSUE TITLE
Plugin upgrade to Rack v0.6

### ISSUE THREAD

**Issue by cschol** [mhetrick/hetrickcv#10]
Hi Michael,

Do you need any help upgrading your plugin to Rack `v0.6`, which is going to be released in the very near future? The API is changing quite a bit, but is stable at this point. The Rack Plugin Repair Team was created to help make the transition easier for plugin developers by providing a GitHub Pull Request with the API required upgrades for `v0.6`.

Let us know and thanks for making this awesome plugin!

**Comment by cschol** [comment]
Well, that actually didn't take long. PR #11.

**Comment by mhetrick** [comment]
Wow, excellent! Thank you so much. I'll compile the binaries and post them to the Releases page once Andrew confirms that the binary interface is ready.
