### ISSUE TITLE
0.6 conversion: many deprecated warnings

### ISSUE THREAD

**Issue by DomiKamu** [mhetrick/hetrickcv#12]
Hi,

During compiling your plugin (Windows platform) against 0.6.0dev, they're a lot of warnings concerning deprecated functions in your source files:
These functions are:

**randomf()**
**clampf** (replaced by **clamp**).

See [258](https://github.com/VCVRack/Rack/issues/258#issuecomment-346222777)
(5th message below "0.5 API" header, Andrew discuss about clampi & clampf deprecated)

I don't know about randomf() function, however, my code doesn't use it.

Cheers.

Dominique

**Comment by mhetrick** [comment]
Hi Dominique! Thanks for the heads up. I've fixed everything on the v1 branch. I will now fix the v1 deprecations as well.
