### ISSUE TITLE
build error against v0.6.1 of Rack API

### ISSUE THREAD

**Issue by 573** [mhetrick/hetrickcv#15]
Ubuntu 16.04

The error was:

>g++ -Wsuggest-override -std=c++11 -fpermissive -DSLUG=HetrickCV -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/RandomGates.cpp.o src/RandomGates.cpp
src/RandomGates.cpp:70:5: error: reference to 'TriggerGenerator' is ambiguous
      TriggerGenerator trigger[8];
      ^
 In file included from src/HetrickCV.hpp:5:0,
                  from src/RandomGates.cpp:1:
 src/HetrickUtilities.hpp:8:8: note: candidates are: struct TriggerGenerator
  struct TriggerGenerator
         ^

**Comment by samhain13** [comment]
Got the same error on Ubuntu 18.04.

**Comment by mhetrick** [comment]
It looks like PulseGenerator (from the VCV SDK) was renamed to TriggerGenerator. I'll need to rename mine to HCVTriggerGenerator.

**Comment by mhetrick** [comment]
Can you pull the latest commit and compile? @573 @samhain13

**Comment by samhain13** [comment]
@mhetrick it works now, thanks!

**Comment by mhetrick** [comment]
Great! I'll close this issue then. Thanks for the heads up on this.
