### ISSUE TITLE
Latest Mac build failing

### ISSUE THREAD

**Issue by lnikj** [mhetrick/hetrickcv#2]
OX X 10.11.6
Rack 0.5dev

Hi Michael

A (rare!) problem with the current Mac build.

Nik

MBP:plugins nik$ rm -rf hetrickcv && git clone https://github.com/mhetrick/hetrickcv.git && cd hetrickcv && make && cd ..
Cloning into 'hetrickcv'...
remote: Counting objects: 349, done.
remote: Compressing objects: 100% (242/242), done.
remote: Total 349 (delta 217), reused 238 (delta 106), pack-reused 0
Receiving objects: 100% (349/349), 5.20 MiB | 4.60 MiB/s, done.
Resolving deltas: 100% (217/217), done.
c++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/ASR.cpp.o src/ASR.cpp
c++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/AToD.cpp.o src/AToD.cpp
c++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7  -std=c++11 -stdlib=libc++ -c -o build/src/Bitshift.cpp.o src/Bitshift.cpp
src/Bitshift.cpp:55:34: error: call to 'abs' is ambiguous
        else shiftedInput = intInput << std::abs(finalShift);
                                        ^~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:664:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:668:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:672:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}
^
1 error generated.
make: *** [build/src/Bitshift.cpp.o] Error 1

**Comment by mhetrick** [comment]
Huh! Look at that. The compiler is claiming that the use of std::abs() (a templated function that returns the absolute value of a number) is ambiguous. 

Can you replace the line
`else shiftedInput = intInput << std::abs(finalShift);`

with
`else
{
    finalShift *= -1;
    shiftedInput = intInput << finalShift;
}`

and let me know if that compiles correctly?

**Comment by lnikj** [comment]
Out and about at the moment, Will test when I get home in a couple of hours.

**Comment by mhetrick** [comment]
No rush. I pushed a new version of Bitshift with that call removed and a few other optimizations. Let me know if the new commit compiles.

**Comment by lnikj** [comment]
That's fixed it. Cheers.
