### ISSUE TITLE
Random Gates outputs 5V in Hold mode

### ISSUE THREAD

**Issue by giogramegna** [mhetrick/hetrickcv#20]
Hello. Just wondering…shouldn’t this module output 10V? Suppose you want to randomize mixer channels via channel CV. By using 5V output gets attenuated.

![](https://community.vcvrack.com/uploads/default/original/2X/c/c4bbc4d258d5c76fbf9d9fc60f74c1b4da15798e.jpeg)

**Comment by mhetrick** [comment]
Thanks for the pull request! I have merged it in.

**Comment by mhetrick** [comment]
Also, congrats on your first pull request!

**Comment by giogramegna** [comment]
Hey Michael! 
Thanks, it was my pleasure to explore your code. I'm still a newbe in this beautiful world of patching racks and coding, but i'm loving it so far.
Have a good time and stay safe at home.
Cheers!


Inviato da iPad
