### ISSUE TITLE
Rotator: patch idea and a humble suggestions

### ISSUE THREAD

**Issue by firolightfog** [mhetrick/hetrickcv#23]
Just to add another Rotator patch idea to the Manual:
![image](https://user-images.githubusercontent.com/34127628/134875211-9471656a-ab75-46ee-8313-b2954fb6d7c1.png)
Selecting from pre-defined notes (like using [Bogaudio REFTONE](https://library.vcvrack.com/Bogaudio/Bogaudio-Reftone) or [Submarine SS-212](https://library.vcvrack.com/SubmarineFree/SS-212)) with a stepped LFO can generate nice (semi-random) tunes.

By the way, could you please change the STAGES knob range from 0-7 to the more meaningful 1-8? 
Also would you please consider adding a TRIGGER input to the Rotator module? 

It could allow feeding any kind of LFO CV to the ROTATE input but let output reshuffle only at the rising edge of the trigger. It'd be a true melody maker... :)

Best regards, Andras

**Comment by mhetrick** [comment]
Hi @S0210 that's a great patch! I'll fix the STAGES tooltip when I get a chance.

Regarding a TRIGGER input, I think that might fill up the interface too much for a less common use case. For your patch, I would suggest sticking a Sample+Hold module of some sort between your modulation signal and the ROTATE input. That will give you the behavior that you expect!

I'll leave this issue open for now and will close it once I get the tooltip fixed.

**Comment by firolightfog** [comment]
Yes, currently I add one more S&H module (or a separate sequencer) to be able to jump from 1 to 3 without going through 2.. I just hoped to save the extra module with a single socket. ;)

Even if you drop this idea, let me put this pic here. See it doesn't look that bad at all, does it? 
![image](https://user-images.githubusercontent.com/34127628/135723966-617d052f-09ce-4ea6-b4fc-7d9d4c8c5153.png)

Good luck for the V2 works! I hope all your modules will be converted for V2 without much hassle! 
 
Best regards, A.

**Comment by biggnome** [comment]
I concur about the labeling thing (I for one also strongly prefer snapping knobs for these sorts of controls with discrete states, but I confess I'm fussy that way).

I also wanted to chime in that the Rotate knob operates backwards to the way it does in the Euro Reakt version, which seems unintuitive to me. (I assume this is a bug/oversight? If I'm mistaken and the Reaktor version was the bugged one, disregard...) To match the original operation, Rotation should be changed from

`const int input = (rotation + i) % stages; `

to

`const int input = (stages - rotation + i) % stages;`

Really great to see you around and maintaining these for the forthcoming update by the way! One of my favorite sets of "it just works" utility & logic modules for sure.

**Comment by mhetrick** [comment]
Just pushed a big commit to spruce up Rotator:
- Tooltips are now correct
- Knob snaps to values
- Rotate direction is now the way it should have been
