### ISSUE TITLE
Problem with makefile

### ISSUE THREAD

**Issue by Torinbob** [mhetrick/hetrickcv#24]
Hi Michael,

I think something may be up with your makefiles. In the HetrickCV one there is an additional forward slash

RACK_DIR ?= ../Rack/
include $(RACK_DIR)/plugin.mk

which results in ../Rack//plugin.mk

but even after fixing that the compiler still can't find plugin.mk (and can't find it in Non Linear Circuits either)

Steve@mac nonlinearcircuits % make -j4
Makefile:6: ../Rack/plugin.mk: No such file or directory
make: *** No rule to make target `../Rack/plugin.mk'.  Stop.

I'm building lots of other v2 plugins successfully and do have plugin.mk in my Rack folder

**Comment by Torinbob** [comment]
I changed the Rack directory to:

RACK_DIR ?= ../..

in the makefiles and all good now.

**Comment by mhetrick** [comment]
Hey @Torinbob, thanks for the heads up. At the moment, the Rack v2 SDK is in flux, so I'm currently pointing to the entire Rack folder (instead of Rack-SDK) on my computer. This will change once the API is stable, and I will resume automated GitHub builds for easy releasing.
