### ISSUE TITLE
Minor bug in 2->4 Mixer

### ISSUE THREAD

**Issue by biggnome** [mhetrick/hetrickcv#28]
Hey, I just noticed the third and fourth outputs seem to be replicating the first two. Changing the '+' to a '-' on line 79 (`outs4[vectorIndex] = insA[vectorIndex] + insB[vectorIndex];`) fixes this.

**Comment by mhetrick** [comment]
Excellent catch! I broke that when updating it for polyphony. Now fixed in https://github.com/mhetrick/hetrickcv/commit/8f69fb9c5ded87a358984ea85d60a977428d7f7f
