### ISSUE TITLE
Phasor->Waveforms crash

### ISSUE THREAD

**Issue by anaday** [mhetrick/hetrickcv#29]
Crash occurs whenever adding module to Rack. Sometimes it's immediate, sometime it takes a while.

Intel Mac 10.15.7 (Catalina)

Not sure if this helps?!
[log.txt](https://github.com/mhetrick/hetrickcv/files/12262824/log.txt)

Fantastic modules. Thanks so much.

**Comment by mhetrick** [comment]
Thanks for the report! I'll look into it. Looks like I'm doing something wrong with the drawing. I had been having random crashes when bulk deleting HetrickCV modules, so that might be the issue module.

**Comment by mhetrick** [comment]
This is likely fixed with https://github.com/mhetrick/hetrickcv/commit/2ebb1fb2e68cfa69911ffe5a1e677ccac495d22d.  Can you test When you have a moment?

**Comment by anaday** [comment]
All good now! Thanks so much
