### ISSUE TITLE
Compiling and Installing

### ISSUE THREAD

**Issue by cmcavoy** [mhetrick/hetrickcv#3]
Hello! I know you're going to release a compiled version, but I spent some time trying to compile and install. Feel free to tell me to "be patient and wait", but maybe this is an easy fix? Here are my notes from the compilation, anything obviously wrong here that you can see? I'm on OSX Sierra

---
Git checkout VCVRack source (HetrickCV uses several libraries as dependencies)
Git checkout VCVrack submodules
Git checkout HetrickCV, put it in the VCVrack source plugins directory
Install GCC if you haven't already, I'm using the XCode command line tools
Brew install dependencies:
brew install jansson
brew install glew
brew install glfw
cd HetrickCV: make all

Here's where I'm having trouble. I copy `plugin.dylib` and the `res` directory to ~/Documents/Rack/plugins/hetrickcv

However, it doesn't show up in Rack. I've tried reloading Rack, I've hit "refresh plugins", nothing. I've downloaded and successfully installed other compiled plugins.

**Comment by cmcavoy** [comment]
Just a note, I discovered `make dist`. Not sure how I missed that. I ran it, then moved dist/HetrickCV into ~/Documents/Rack/plugins. It's still not picking it up.

**Comment by mhetrick** [comment]
If you're compiling VCV Rack from source, try this:
-Change to the base Rack directory.
-Run `git pull` to ensure that you're on the latest version of Rack.
-Run `make` to build the Rack itself.
-Run `make allplugins` to build everything in the plugins directory.
-Run `make run` to launch the dev version of Rack.

(If any of the other plugins fail to build during the `make allplugins` phase, you may need to switch to each plugin directory and run a `git pull` to update each repo)

**Comment by cmcavoy** [comment]
Ah, so I can't just compile your plugin? I'd need to compile VCV Rack from source as well?

**Comment by mhetrick** [comment]
Unfortunately, at the moment, yes. There were changes to how plugin bundles are organized, which is why the compiled binaries aren't showing up in the 0.4.0 app. I'm able to run both the dev Rack and release Rack on my computer without issues, so it may be worth having both if you want to try lots of plugins :)

**Comment by cmcavoy** [comment]
Got it, thanks for the follow up! I'll go ahead and close this issue. I'll try compiling the whole package.

Thanks!
