### ISSUE TITLE
[gate junction] typo in reset and randomize

### ISSUE THREAD

**Issue by phdsg** [mhetrick/hetrickcv#4]
doesn't break building, but throws errors.
lines 102 and 110
`for (int i = 0; i < 10; i++)`
should be
`for (int i = 0; i < 8; i++)`

**Comment by mhetrick** [comment]
Thank you! Good catch. This is fixed in https://github.com/mhetrick/hetrickcv/commit/d3ad88a800db06707f831047d4f187045c8ca731
