### ISSUE TITLE
Really would like to testdrive your new version (5) plugins ! How ?

### ISSUE THREAD

**Issue by 2johjoh2** [mhetrick/hetrickcv#6]
Don't know if it is possible, but just asking : is there any rack version (compiled or manual make) that allows to use your compiled versions, or is the only way for testing to build them from source inside a current rack dev (self-)built ? (this is probably not the right place to ask, but don't want to flood the FB page with too many messages ...

**Comment by mhetrick** [comment]
Thanks! The only way to use them at the moment is to compile the Rack source code. The 0.5.0 Rack binary should be up within the next day. Andrew posted his 36-hour notice for developers on the Facebook page yesterday or Saturday.

**Comment by mhetrick** [comment]
As a heads up, the official 0.5.0 Rack binary is now available from the site. I've updated the HetrickCV binary to 0.5.1 to fix a minor bug. Let me know if this works for you!
