### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by t0m5k1** [mhetrick/hetrickcv#7]
Please can we have a Linux release?

**Comment by phdsg** [comment]
[HetrickCV-devf817677-lin.zip](https://github.com/mhetrick/hetrickcv/files/1503874/HetrickCV-devf817677-lin.zip)

**Comment by t0m5k1** [comment]
Thank you so much :)

**Comment by lazzarello** [comment]
Does it not build on Linux? It compiles fine for me on macOS.

**Comment by mhetrick** [comment]
It builds, but I just need to put together a convenient workflow for doing so. I want the Linux version to be up-to-date with the other builds.

**Comment by mhetrick** [comment]
Linux builds are now available on the Releases page. They will be up on the Plugin Manager shortly.

**Comment by phdsg** [comment]
linux 0.5.4 from the releases page doesn't load on my debian.

`[warning] Failed to load library ./plugins/HetrickCV/plugin.so: ./plugins/HetrickCV/plugin.so: undefined symbol: _ZN4rack11assetPluginEPNS_6PluginESs
`

here's a build that should work:
[HetrickCV-0.5.4-lin.zip](https://github.com/mhetrick/hetrickcv/files/1595443/HetrickCV-0.5.4-lin.zip)

**Comment by mhetrick** [comment]
@phdsg, can you let me know if this build works? I've compiled it on a different machine with a more thorough process.

[HetrickCV-0.5.4-lin.zip](https://github.com/mhetrick/hetrickcv/files/1598069/HetrickCV-0.5.4-lin.zip)

**Comment by phdsg** [comment]
good!

**Comment by phdsg** [comment]
saw your question on fb concerning linux builds. (can't post there anymore. someone reported my account to the name police)
i used to do the linux building on debian9 in a virtualbox.
used this guide http://nikjewell.net/vcvrack/setting_up.html after the os was installed to meet all the dependencies for rack. then the whole rack setup.
i have a clone of this on a laptop now, but still use the vm occasionally.

**Comment by mhetrick** [comment]
Closing this, as the last few Linux builds seem to be working (no one has written to say otherwise). Just for reference: I've been using the Windows 10 Ubuntu Subsystem to produce these.
