### ISSUE TITLE
Install with Plugin Manager

### ISSUE THREAD

**Issue by briansorahan** [mhetrick/hetrickcv#8]
Adding this plugin through the [Plugin Manager](https://vcvrack.com/plugins.html) did not work for some reason.
I'm using Rack v0.5 on Arch Linux.
I was able to start using your modules by compiling manually.

**Comment by mhetrick** [comment]
Unfortunately, there's not a pre-built Linux binary yet. I'm glad to hear that it's working on the platform, though. I'll figure out a good workflow for compiling it soon so that I can keep Linux builds up-to-date.

**Comment by briansorahan** [comment]
@mhetrick That would be awesome. How do you compile the mac and win releases? Hopefully it's easy to include a linux artifact in your existing workflow.

**Comment by mhetrick** [comment]
Just added official Linux builds! They will be available on the Plugin Manager once the pull request goes through.
