### ISSUE TITLE
ES5 encoder?

### ISSUE THREAD

**Issue by dar2dar2** [mhetrick/hetrickcv#9]
Hi!
Just wanted to knew if you were planning to port your es5encoder from reaktor into VCV?

Tried to do it yesterday by starting from your DtoA module and observing the patches on reaktor but obvioulsly i don't know what i'm doing as i'm don't know a thing in c++ (i had some results but can't manage to get outputs 7 and 8 working and got some short burst on every outputs).

Thanks.
Best regards.

**Comment by mhetrick** [comment]
I had been meaning to do this but just never found the time. Thankfully, Expert Sleepers now have an official encoder: https://expert-sleepers.co.uk/vcvrack_encoders.html
